// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaPro2G5.DAL.Data;

#nullable disable

namespace PracticaPro2G5.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703011628_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PracticaPro2G5.DAL.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Bisturís, pinzas, tijeras y material de quirófano.",
                            Nombre = "Instrumental quirúrgico"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Gasas, vendas, apósitos y antisépticos.",
                            Nombre = "Material de curación"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Termómetros, tensiómetros y estetoscopios.",
                            Nombre = "Equipo de diagnóstico"
                        });
                });

            modelBuilder.Entity("PracticaPro2G5.DAL.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("Descripcion");

                    b.Property<int>("FkCategoria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FkCategoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Precio");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Stock");

                    b.HasKey("Id");

                    b.HasIndex("FkCategoria");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("PracticaPro2G5.DAL.Entidades.Producto", b =>
                {
                    b.HasOne("PracticaPro2G5.DAL.Entidades.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("FkCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PracticaPro2G5.DAL.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
